version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)
  [![Developed by: Cisco](https://img.shields.io/badge/Developed%20by-Cisco-blue)](https://developer.cisco.com)

  # Terraform Intersight Profiles - Server
  Manages Intersight Server Profiles
  
  Location in GUI:
  `Profiles` » `Create Profile` » `Server`

  ## Easy IMM

  [*Easy IMM - Comprehensive Example*](https://github.com/terraform-cisco-modules/easy-imm-comprehensive-example) - A comprehensive example for policies, pools, and profiles.

  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### provider.tf
  ```hcl
  {{ include "examples/complete/provider.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with the value of [your-api-key]
  - Add variable secretkey with the value of [your-secret-file-content]

  ### Linux and Windows
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkeyfile="<secret-key-file-location>"
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false