version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Server Profile Example

  ### main.tf
  ```hcl
  {{ include "./main.tf" }}
  ```

  ### provider.tf
  ```hcl
  {{ include "./provider.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "./variables.tf" }}
  ```

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with the value of [your-api-key]
  - Add variable secretkey with the value of [your-secret-file-content]

  ### Linux and Windows
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkeyfile="<secret-key-file-location>"
  ```

  To run this example you need to execute:

  ```bash
  terraform init
  terraform plan -out="main.plan"
  terraform apply "main.plan"
  ```

  Note that this example will create resources. Resources can be destroyed with `terraform destroy`.

output:
  file: README.md
  mode: replace